idf_component_register(
    SRCS
        "main.cpp"
        "boot/boot_trace.cpp"
        "boot/power_log.cpp"
        "hal/hal_power.cpp"
        "hal/hal_display.cpp"
        "hal/hal_sensors.cpp"
        "hal/hal_rtc.cpp"
        "hal/hal_sd.cpp"
        "hal/hal_audio.cpp"
        "hal/hal_input.cpp"
        "ui/text_outline.cpp"
        "ui/w_statusbar.cpp"
        "ui/w_cardview.cpp"
        "ui/screen.cpp"
        "content/deck.cpp"
        "app/app.cpp"
        "app/console_cmds.cpp"
        "content/builtin_cards.cpp"
    INCLUDE_DIRS
        "."
    EMBED_FILES
        "embedded/apple.png"
        "embedded/apple.wav"
        "embedded/cat.png"
        "embedded/cat.wav"
        "embedded/statusbar.png"
        "embedded/letters/ltr_a.wav"
        "embedded/letters/ltr_b.wav"
        "embedded/letters/ltr_c.wav"
        "embedded/letters/ltr_d.wav"
        "embedded/letters/ltr_e.wav"
        "embedded/letters/ltr_f.wav"
        "embedded/letters/ltr_g.wav"
        "embedded/letters/ltr_h.wav"
        "embedded/letters/ltr_i.wav"
        "embedded/letters/ltr_j.wav"
        "embedded/letters/ltr_k.wav"
        "embedded/letters/ltr_l.wav"
        "embedded/letters/ltr_m.wav"
        "embedded/letters/ltr_n.wav"
        "embedded/letters/ltr_o.wav"
        "embedded/letters/ltr_p.wav"
        "embedded/letters/ltr_q.wav"
        "embedded/letters/ltr_r.wav"
        "embedded/letters/ltr_s.wav"
        "embedded/letters/ltr_t.wav"
        "embedded/letters/ltr_u.wav"
        "embedded/letters/ltr_v.wav"
        "embedded/letters/ltr_w.wav"
        "embedded/letters/ltr_x.wav"
        "embedded/letters/ltr_y.wav"
        "embedded/letters/ltr_z.wav"
    REQUIRES
        driver
        esp_driver_gpio
        esp_driver_i2s
        esp_driver_usb_serial_jtag
        esp_driver_spi
        esp_driver_sdspi
        esp_timer
        esp_psram
        fatfs
        sdmmc
        console
        nvs_flash
        json
        esp_app_format
        spi_flash
        vfs
)
