idf_component_register(
    SRCS
        "main.cpp"
        "boot/boot_trace.cpp"
        "hal/hal_power.cpp"
        "hal/hal_display.cpp"
        "hal/hal_sensors.cpp"
        "hal/hal_rtc.cpp"
        "hal/hal_sd.cpp"
        "hal/hal_audio.cpp"
        "hal/hal_input.cpp"
        "ui/text_outline.cpp"
        "ui/w_statusbar.cpp"
        "ui/w_cardview.cpp"
        "ui/screen.cpp"
        "content/deck.cpp"
        "app/app.cpp"
        "app/console_cmds.cpp"
        "content/builtin_cards.cpp"
    INCLUDE_DIRS
        "."
    EMBED_FILES
        "embedded/apple.png"
        "embedded/apple.wav"
        "embedded/cat.png"
        "embedded/cat.wav"
        "embedded/statusbar.png"
    REQUIRES
        driver
        esp_driver_gpio
        esp_driver_i2s
        esp_driver_usb_serial_jtag
        esp_driver_spi
        esp_driver_sdspi
        esp_timer
        esp_psram
        fatfs
        sdmmc
        console
        nvs_flash
        json
        esp_app_format
        spi_flash
        vfs
)
