/*
 * The phonics deck: 26 letters x 5 word/picture/audio triples, described by a
 * JSON manifest on the microSD card and generated by tools/gen_assets.py.
 *
 * Manifest layout (/sd/phonics/manifest.json):
 *
 *   {
 *     "version": 1,
 *     "voice": "en_US-libritts-high",
 *     "cards": [
 *       { "id": "p_apple", "letter": "P", "display": "aPPle",
 *         "span": [1, 2],
 *         "image": "cards/p/apple.png",
 *         "audio": "cards/p/apple.wav" }
 *     ]
 *   }
 *
 * `display` carries the exact casing to render: the grapheme that makes the
 * taught sound is uppercase, everything else lowercase. `span` is the
 * [offset, length] of that grapheme inside `display`, so the renderer can
 * colour it without re-deriving the rule on-device.
 */
#pragma once

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <esp_err.h>

namespace content {

struct Card {
    char id[40];        // "p_apple"
    char letter;        // 'A'..'Z'
    char display[32];   // "aPPle"
    int8_t span_start;  // grapheme offset within display
    int8_t span_len;    // grapheme length
    char image[112];    // absolute path, e.g. /sd/phonics/cards/p/apple.png
    char audio[112];    // absolute path

    // Non-null for cards baked into the firmware image. When set, the assets
    // are read straight out of memory-mapped flash and the path fields are
    // only labels -- so the device is fully testable with no microSD card.
    const unsigned char* image_data;
    unsigned int image_len;
    const unsigned char* audio_data;
    unsigned int audio_len;

    bool isBuiltin() const { return image_data != nullptr; }
};

/// Allocate the card table and register the firmware's built-in cards.
/// Call before load(); the built-ins stay in the rotation even when an SD
/// deck loads on top of them.
esp_err_t begin();

/// Parse the manifest and append to the card table.
/// `verify_assets` stats every referenced file and drops cards whose image or
/// audio is missing, which turns a half-copied SD card into a clear warning
/// instead of a mystery blank screen later.
esp_err_t load(const char* manifest_path, bool verify_assets = true);

bool loaded();
size_t cardCount();
size_t letterCount();
size_t droppedCount();

/// One-line description for boot traces, e.g. "130 cards, 26 letters".
const char* stats();

const Card* current();

/// Pick a card at random: a random letter, then a word for that letter.
///
/// Among that letter's words, one where the taught grapheme is the word's
/// FIRST letter is preferred with probability kInitialGraphemeBias. Initial
/// sounds are easier to hear, so they should dominate, but medial and final
/// examples (bUg, boX, siX) still need to show up.
///
/// Never returns the same card twice in a row.
const Card* advanceRandom();

/// Probability of preferring a word-initial grapheme in advanceRandom().
constexpr float kInitialGraphemeBias = 0.60f;

/// Next card in a shuffled playlist covering the whole deck; reshuffles and
/// wraps when exhausted. Kept for the `next` console command.
const Card* advance();

/// First card of the next letter that has any cards.
const Card* advanceLetter();

/// Pick explicitly (used by the `card` console command). `nth` is 0-based and
/// wraps within that letter. Returns nullptr if the letter has no cards.
const Card* selectLetter(char letter, int nth);

int cardsForLetter(char letter);

// --- Built-in (in-flash) cards, defined in builtin_cards.cpp --------------
size_t builtinCardCount();
bool fillBuiltinCard(size_t index, Card* out);

}  // namespace content
