/*
 * Visual theme + screen geometry.
 *
 * COLOURS: the Spectra 6 panel can only render six inks. These constants are
 * the *exact* RGB triplets from Panel_ED2208's internal `epd_palette`, so
 * anything drawn in them survives the driver's nearest-colour lookup
 * unchanged -- no surprise remapping, no muddy in-between shades.
 */
#pragma once

#include <cstdint>

namespace ui::theme {

// --- Panel-native palette (do not invent colours outside this set) ---------
constexpr uint32_t kBlack  = 0x000000u;
constexpr uint32_t kWhite  = 0xFFFFFFu;
constexpr uint32_t kYellow = 0xFFF338u;
constexpr uint32_t kRed    = 0xBF0000u;
constexpr uint32_t kBlue   = 0x6440FFu;
constexpr uint32_t kGreen  = 0x438A1Cu;

// --- Semantic roles --------------------------------------------------------
constexpr uint32_t kBackground   = kWhite;
constexpr uint32_t kInk          = kBlack;   // primary text
constexpr uint32_t kAccentRule   = kBlue;    // divider under the status bar
constexpr uint32_t kFrame        = kBlack;   // image frame
constexpr uint32_t kWordFill     = kWhite;   // word interior
constexpr uint32_t kWordOutline  = kBlack;   // word outline
constexpr uint32_t kGraphemeFill = kRed;     // the letter(s) making the sound

// Highlight the taught grapheme in kGraphemeFill instead of plain white.
// The uppercase/lowercase split already encodes which letters make the sound;
// this adds a second, colour-coded cue. Set to false for a strictly
// white-fill-on-black-outline word, as originally specced.
constexpr bool kAccentGrapheme = true;

// Paint the status bar with a colour gradient rather than a flat white strip.
// The gradient itself is a pre-dithered PNG generated by tools/gen_chrome.py
// and embedded in the firmware -- a six-ink panel cannot render a smooth
// sweep directly, and flat bands look like flat bands. kStatusBands below is
// only the fallback if that blob fails to decode. The bar's text switches to
// white-with-black-outline when this is on, which stays legible over any hue.
constexpr bool kStatusRainbow = true;
constexpr uint32_t kStatusBands[] = {kRed, kYellow, kGreen, kBlue};
constexpr int kStatusBandCount =
    static_cast<int>(sizeof(kStatusBands) / sizeof(kStatusBands[0]));
constexpr int kStatusTextOutlineRadius = 2;

// --- Screen geometry (portrait 400x600) ------------------------------------
//
// Region positions are chosen to sit next to the PHYSICAL buttons, so the
// on-screen hints point at the right hardware:
//   * the top button is in the middle of the title bar  -> hint centred, just
//     below the bar, with an arrow pointing UP into it
//   * the two side buttons are on the LEFT edge, the first just below the
//     title bar and the second one line lower -> hints in a left gutter with
//     arrows pointing LEFT
// The lowest side button is PWR_KEY and is deliberately unlabelled.
constexpr int16_t kScreenW = 400;
constexpr int16_t kScreenH = 600;

// Upper status bar: date, time, temperature, humidity.
constexpr int16_t kStatusX = 0;
constexpr int16_t kStatusY = 0;
constexpr int16_t kStatusW = 400;
constexpr int16_t kStatusH = 64;

// Divider rule directly beneath the status bar.
constexpr int16_t kRuleY = 64;
constexpr int16_t kRuleH = 3;

// Hint for the TOP button: centred immediately under the status bar.
constexpr int16_t kHintTopY = 69;
constexpr int16_t kHintTopH = 22;

// Left gutter holding the two side-button hints.
constexpr int16_t kGutterX = 0;
constexpr int16_t kGutterW = 66;
constexpr int16_t kHintSide1Y = 96;    // just below the status bar
constexpr int16_t kHintSide2Y = 124;   // one line lower
constexpr int16_t kHintRowH = 22;

// Square image area, to the right of the gutter.
constexpr int16_t kImageX = 72;
constexpr int16_t kImageY = 94;
constexpr int16_t kImageW = 320;
constexpr int16_t kImageH = 320;

// Word band -- the biggest region on the screen, because the word is the
// point of the device.
constexpr int16_t kWordX = 0;
constexpr int16_t kWordY = 420;
constexpr int16_t kWordW = 400;
constexpr int16_t kWordH = 174;

// Horizontal breathing room reserved either side of the word, on top of the
// outline radius, so a long word never touches the bezel.
constexpr int16_t kWordSideMargin = 6;

// Hint text metrics.
constexpr int16_t kArrowSize = 7;

// --- Metrics ---------------------------------------------------------------
constexpr int kFrameThickness = 3;
constexpr uint32_t kHintInk = kBlack;
constexpr int kWordOutlineRadius = 3;

}  // namespace ui::theme
